name: Deploy Static Web App - Frontend - Mr Tracker Dev
# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
      [ 'frontend/**', '.github/workflows/frontend-dev.yml' ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v5
        with:
          submodules: true  # Fetches submodules

      - name: Replace backend URL placeholder in staticwebapp config
        run: |
          # 1. Export the variable so envsubst can find it.
          #    (Using 'export' is cleaner in a script block).
          export BACKEND_URL=${{ secrets.BACKEND_API_URL_DEV }}

          # 2. Run envsubst, writing to a new temporary file.
          #    The '$BACKEND_URL' tells envsubst to ONLY replace this one variable.
          envsubst '$BACKEND_URL' < ./frontend/staticwebapp.config.json > ./frontend/staticwebapp.config.json

          # 3. Overwrite the original file with the new one.
          mv ./frontend/staticwebapp.config.json ./frontend/staticwebapp.config.json
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.FRONTEND_WEB_APP_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
 